<a href="https://colab.research.google.com/github/2303A51717/2303A51717_b11_pds/blob/main/lab3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [16]:
import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
print("Array arr1:", arr1)
print("Array arr2:", arr2)
print("arr1 + arr2:", arr1+arr2)
print("arr1 - arr2:", arr1-arr2)
print("arr1 * arr2:", arr1*arr2)
print("arr1 / arr2:", arr1/arr2)
print("arr1**2:", arr1**2)
print("arr2**2:", arr2**2)
print("arr1 % 3:", arr1%3)
print("arr2 % 4:", arr2%4)
print("Sum of arr1 + arr2:", np.sum(arr1+arr2))
print("Subtract arr1 from arr2:", np.subtract(arr1,arr2))
print("Multiply arr1 and arr2:", np.multiply(arr1,arr2))
print("Divide arr1 by arr2:", np.divide(arr1,arr2))

Array arr1: [1 2 3]
Array arr2: [4 5 6]
arr1 + arr2: [5 7 9]
arr1 - arr2: [-3 -3 -3]
arr1 * arr2: [ 4 10 18]
arr1 / arr2: [0.25 0.4  0.5 ]
arr1**2: [1 4 9]
arr2**2: [16 25 36]
arr1 % 3: [1 2 0]
arr2 % 4: [0 1 2]
Sum of arr1 + arr2: 21
Subtract arr1 from arr2: [-3 -3 -3]
Multiply arr1 and arr2: [ 4 10 18]
Divide arr1 by arr2: [0.25 0.4  0.5 ]


question-2

In [34]:
import numpy as np
import matplotlib.pyplot as plt
arr1=np.array([[[1,2],[3,4],[5,6]]])
arr2=np.array([[10,20,30],[40,50,60]])
print("Array arr1:", arr1)
print("Array arr2:", arr2)
print("Dot product:",arr1.dot(arr2))
print("Dot product:",arr1@arr2)
image = np.array([[100, 150],
                  [200, 250]])
filter_matrix = np.array([[0.5, 0.2],
                           [0.3, 0.8]])

print("\nOriginal 'image' matrix:")
print(image)
print("\nFilter matrix:")
print(filter_matrix)

# Applying filter using dot product
filtered_image = np.dot(image, filter_matrix)
print("\nFiltered image matrix (after transformation):")
print(filtered_image)

# Step 5: Visualization
fig, axes = plt.subplots(1, 2, figsize=(6, 3))
axes[0].imshow(image, cmap='gray')
axes[0].set_title("Original Image")
axes[0].axis("off")

axes[1].imshow(filtered_image, cmap='gray')
axes[1].set_title("Filtered Image")
axes[1].axis("off")

plt.tight_layout()
plt.show()

Array arr1: [[[1 2]
  [3 4]
  [5 6]]]
Array arr2: [[10 20 30]
 [40 50 60]]
Dot product: [[[ 90 120 150]
  [190 260 330]
  [290 400 510]]]
Dot product: [[[ 90 120 150]
  [190 260 330]
  [290 400 510]]]

Original 'image' matrix:
[[100 150]
 [200 250]]

Filter matrix:
[[0.5 0.2]
 [0.3 0.8]]

Filtered image matrix (after transformation):
[[ 95. 140.]
 [175. 240.]]
